# tomcat (container)
server:
  port: 8080
  servlet:
    context-path: /bootbox
# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
# logback (logging)
logging:
  level:
    root: info
    com.sh.app: debug