# tomcat (container)
server:
  port: 8080
  servlet:
    context-path: /bootbox
# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
#    url: ${PROD_DB_URL}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: test_bootbox
    password: test_bootbox
  jpa:
    generate-ddl: true
    show-sql: true #만들어진 쿼리를 보여줄것인가? true or false
    properties:
      hibernate:
        format_sql: true #false일시 한 줄로 나옴
        hbm2ddl:
          auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
# logback (logging)
logging:
  level:
    root: info
    com.sh.app: debug