# tomcat (container)
server:
  port: 8080
  servlet:
    context-path: /bootbox
# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: bootbox
#    password: bootbox
  jpa:
    generate-ddl: true
    show-sql: true #만들어진 쿼리를 보여줄것인가? true or false
    properties:
      hibernate:
        format_sql: true #false일시 한 줄로 나옴
        hbm2ddl:
          #create:entity로 등록한 모든 테이블을 생성하기때문에 member table만 작업하는것따윈없다..
          auto: update #ddl 생성옵션 (개발극초기:create,create-drop/개발중:update/종료후:validate
      database: oracle
      database-platform: org.hibernate.dialect.OracleDialect
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
      mode: never
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b01bd8d24bd31d50e3202dfe20900871
            client-secret: 0qL7cVTSU3GZ5l0SZogkd4QGpuAM2Wr3
            redirect-uri: http://localhost:8080/spring/login/oauth2/code/kakao
            client-authentication-method: 'client_secret_post'
            client-name: kakao
            authorization-grant-type: authorization_code
          google:
            client-id: 391591937965-gj682k5kpfu6cp5l6oem3u56fikb5k1l.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 인증 서버
            token-uri: https://kauth.kakao.com/oauth/token # 인증 서버
            user-info-uri: https://kapi.kakao.com/v2/user/me # resource 서버
            user-info-authentication-method: POST
            user-name-attribute: id
# logback (logging)
logging:
  level:
    root: info
    com.sh.app: debug
  # profile 관리
  spring:
    profiles:
#      default: test
      active: prod