# tomcat (container)
server:
  port: 8080
  servlet:
    context-path: /bootbox
# database
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@whi0m2vf43suz8ly_high?TNS_ADMIN=C:/Workspaces/final_bootbox/bootbox/wallets/Wallet_WHI0M2VF43SUZ8LY
    username: bootbox
    password: "Code_director240226@123"
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
# logback (logging)
logging:
  level:
    root: info
    com.sh.app: debug